import type { Metadata } from 'next'
import './globals.css'
import TopNav from './components/topNav';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <TopNav />
                {children}
            </body>
        </html>
    )
}